[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.33.0"
ci = []
hosting = ["github"]
installers = []
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
install-updater = false
source-tarball = false
checksum = "sha256"

[dist.min-glibc-version]
"*" = "2.28"
