[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.33.0"
ci = []
hosting = ["github"]
installers = []
targets = ["aarch64-apple-darwin"]
install-updater = false
source-tarball = false
checksum = "sha256"

[dist.min-glibc-version]
"*" = "2.28"
